FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    default-libmysqlclient-dev \
    pkg-config \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir sqlalchemy pymysql pandas python-dotenv

COPY scripts/ ./scripts/
COPY db/ ./db/

CMD ["python", "scripts/load_csv.py"]